from PySide2 import QtWidgets
from PySide2 import QtCore, QtGui
from PySide2.QtWidgets import QApplication, QWidget, QAbstractItemView
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import hou
import os
import sys
import datetime as datetime
from hou import SopNode, Node


class MainWindow(QtWidgets.QDialog):
    def __init__(self, parm=None, parent=hou.qt.mainWindow()):
        super(MainWindow, self).__init__(parent)
        self.mainWindow()

    def mainWindow(self):
        self.setWindowTitle("Alembic Importer")
        self.setMinimumSize(QSize(550, 650))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main = QtWidgets.QVBoxLayout()
        self.main.setSpacing(0)
        self.main.setObjectName("main")
        self.widgetNameWidget = QtWidgets.QWidget(self)
        self.widgetNameWidget.setMaximumSize(QtCore.QSize(16777215, 55))
        self.widgetNameWidget.setObjectName("widgetNameWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetNameWidget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widgetNameWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.main.addWidget(self.widgetNameWidget, 0, QtCore.Qt.AlignHCenter)
        self.refreshWidget = QtWidgets.QWidget(self)
        self.refreshWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.refreshWidget.setObjectName("refreshWidget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.refreshWidget)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.refreshBtn = QtWidgets.QPushButton(self.refreshWidget)
        self.refreshBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font1 = QtGui.QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.refreshBtn.setFont(font1)
        self.refreshBtn.setObjectName("refreshBtn")
        self.horizontalLayout_16.addWidget(self.refreshBtn)
        self.main.addWidget(self.refreshWidget)
        self.pathWidget = QtWidgets.QWidget(self)
        self.pathWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pathWidget.setObjectName("pathWidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.pathWidget)
        self.horizontalLayout_17.setContentsMargins(-1, 6, 9, 6)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_10 = QtWidgets.QWidget(self.pathWidget)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.selectFolderBtn = QtWidgets.QPushButton(self.widget_10)
        self.selectFolderBtn.setObjectName("selectFolderBtn")
        self.horizontalLayout_18.addWidget(self.selectFolderBtn)
        self.horizontalLayout_17.addWidget(self.widget_10)
        self.widget_14 = QtWidgets.QWidget(self.pathWidget)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.abcpathField = QtWidgets.QLineEdit(self.widget_14)
        self.abcpathField.setInputMask("")
        self.abcpathField.setObjectName("abcpathField")
        self.horizontalLayout_19.addWidget(self.abcpathField)
        self.horizontalLayout_17.addWidget(self.widget_14)
        self.main.addWidget(self.pathWidget)
        self.tableWidget = QtWidgets.QWidget(self)
        self.tableWidget.setObjectName("tableWidget")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.tableWidget)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.abcTableWidget = QtWidgets.QTableWidget(self.tableWidget)
        self.abcTableWidget.setObjectName("abcTableWidget")
        self.abcTableWidget.setColumnCount(2)
        self.abcTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.abcTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.abcTableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_20.addWidget(self.abcTableWidget)
        self.main.addWidget(self.tableWidget)
        self.sopsWidget = QtWidgets.QWidget(self)
        self.sopsWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sopsWidget.setObjectName("sopsWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.sopsWidget)
        self.horizontalLayout_5.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.sopsWidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.chkBxIncludeSubfolders = QtWidgets.QCheckBox(self.widget_7)
        self.chkBxIncludeSubfolders.setObjectName("chkBxIncludeSubfolders")
        self.horizontalLayout_10.addWidget(self.chkBxIncludeSubfolders)
        self.horizontalLayout_9.addWidget(self.widget_7)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.sopsWidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.chkBxAddTransform = QtWidgets.QCheckBox(self.widget_9)
        self.chkBxAddTransform.setObjectName("chkBxAddTransform")
        self.horizontalLayout_11.addWidget(self.chkBxAddTransform)
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.sopsWidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.widget_5)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.chkBxAddConvert = QtWidgets.QCheckBox(self.widget_11)
        self.chkBxAddConvert.setObjectName("chkBxAddConvert")
        self.horizontalLayout_12.addWidget(self.chkBxAddConvert)
        self.horizontalLayout_7.addWidget(self.widget_11)
        self.horizontalLayout_5.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.sopsWidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_13 = QtWidgets.QWidget(self.widget_6)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.chkBxAddNormal = QtWidgets.QCheckBox(self.widget_13)
        self.chkBxAddNormal.setObjectName("chkBxAddNormal")
        self.horizontalLayout_13.addWidget(self.chkBxAddNormal)
        self.horizontalLayout_6.addWidget(self.widget_13)
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.widget_8 = QtWidgets.QWidget(self.sopsWidget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_12 = QtWidgets.QWidget(self.widget_8)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.chkBxAddFileCache = QtWidgets.QCheckBox(self.widget_12)
        self.chkBxAddFileCache.setObjectName("chkBxAddFileCache")
        self.horizontalLayout_15.addWidget(self.chkBxAddFileCache)
        self.horizontalLayout_14.addWidget(self.widget_12)
        self.horizontalLayout_5.addWidget(self.widget_8)
        self.main.addWidget(self.sopsWidget)
        self.buttonsWidget = QtWidgets.QWidget(self)
        self.buttonsWidget.setMaximumSize(QtCore.QSize(16777215, 45))
        self.buttonsWidget.setObjectName("buttonsWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonsWidget)
        self.horizontalLayout_2.setContentsMargins(-1, 7, -1, 7)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.buttonsWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.executeBtn = QtWidgets.QPushButton(self.widget)
        self.executeBtn.setObjectName("executeBtn")
        self.horizontalLayout_3.addWidget(self.executeBtn)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.buttonsWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cancelBtn = QtWidgets.QPushButton(self.widget_2)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_4.addWidget(self.cancelBtn)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.main.addWidget(self.buttonsWidget)
        self.verticalLayout_2.addLayout(self.main)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Bulk Alembic Importer v1.1.0"))
        self.label.setText(_translate("Form", "Bulk Alembic Importer v1.1.0"))
        self.refreshBtn.setText(_translate("Form", "Refresh UI"))
        self.selectFolderBtn.setText(_translate("Form", "Select Folder"))
        self.abcpathField.setPlaceholderText(_translate("Form", "ABC path.............."))
        item = self.abcTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ABC Files"))
        item = self.abcTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Date Modified"))
        self.chkBxIncludeSubfolders.setText(_translate("Form", "Include SubFolders"))
        self.chkBxAddTransform.setText(_translate("Form", "Add Transform"))
        self.chkBxAddConvert.setText(_translate("Form", "Add Convert"))
        self.chkBxAddNormal.setText(_translate("Form", "Add Normal"))
        self.chkBxAddFileCache.setText(_translate("Form", "Add File Cache"))
        self.executeBtn.setText(_translate("Form", "Execute"))
        self.cancelBtn.setText(_translate("Form", "Cancel"))

dialog = MainWindow()
dialog.show()